### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by Raporaz03** [NiteeshK21/HotelManagement#7]
hello I  will update your documentation by adding :
*More details 
*Adding gifs and images so that it will look better

**Comment by Raporaz03** [comment]
can i do it ?

**Comment by NiteeshK21** [comment]
Yes, of course!

**Comment by Raporaz03** [comment]
So I am starting update 
updated

**Comment by NiteeshK21** [comment]
Great Work! 👏
